/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UHhN5XuCp1l
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"

export function Recipes() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-8 md:py-12">
        <div className="container">
          <div className="grid md:grid-cols-2 gap-8 items-center">
            <div>
              <h1 className="text-3xl md:text-5xl font-bold mb-4">Discover Delicious Recipes</h1>
              <p className="text-lg md:text-xl mb-6">Find inspiration for your next meal with our featured recipes.</p>
              <div className="relative">
                <Input
                  type="search"
                  placeholder="Search recipes..."
                  className="w-full rounded-md pl-10 pr-4 py-2 focus:outline-none focus:ring-2 focus:ring-primary-foreground"
                />
                <SearchIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-primary-foreground" />
              </div>
            </div>
            <div className="hidden md:block">
              <img
                src="/placeholder.svg"
                width={500}
                height={400}
                alt="Featured Recipe"
                className="rounded-lg object-cover"
              />
            </div>
          </div>
        </div>
      </header>
      <main className="container py-12 md:py-16">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="col-span-1 md:col-span-1">
            <div className="bg-muted rounded-lg p-6">
              <h2 className="text-lg font-bold mb-4">Categories</h2>
              <nav>
                <ul className="space-y-2">
                  <li>
                    <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
                      Appetizers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
                      Main Dishes
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
                      Desserts
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
                      Drinks
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
                      Salads
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
                      Soups
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
            <div className="bg-muted rounded-lg p-6 mt-6">
              <h2 className="text-lg font-bold mb-4">Dietary Filters</h2>
              <div className="space-y-2">
                <Label className="flex items-center gap-2">
                  <Checkbox id="vegetarian" />
                  Vegetarian
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="vegan" />
                  Vegan
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="gluten-free" />
                  Gluten-Free
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="dairy-free" />
                  Dairy-Free
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="paleo" />
                  Paleo
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="keto" />
                  Keto
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="low-carb" />
                  Low-Carb
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="nut-free" />
                  Nut-Free
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="soy-free" />
                  Soy-Free
                </Label>
                <Label className="flex items-center gap-2">
                  <Checkbox id="seafood-free" />
                  Seafood-Free
                </Label>
              </div>
            </div>
          </div>
          <div className="col-span-1 md:col-span-3">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="bg-muted rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={250}
                  alt="Recipe Image"
                  className="w-full h-48 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Creamy Mushroom Risotto</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A rich and creamy risotto made with earthy mushrooms and parmesan cheese.
                  </p>
                </div>
              </div>
              <div className="bg-muted rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={250}
                  alt="Recipe Image"
                  className="w-full h-48 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Grilled Salmon with Lemon Dill Sauce</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    Tender salmon fillets grilled to perfection and topped with a bright, tangy lemon dill sauce.
                  </p>
                </div>
              </div>
              <div className="bg-muted rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={250}
                  alt="Recipe Image"
                  className="w-full h-48 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Vegetable Stir-Fry with Tofu</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A colorful and flavorful stir-fry with crisp vegetables and marinated tofu.
                  </p>
                </div>
              </div>
              <div className="bg-muted rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={250}
                  alt="Recipe Image"
                  className="w-full h-48 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Chocolate Lava Cake</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A decadent and indulgent chocolate cake with a molten, fudgy center.
                  </p>
                </div>
              </div>
              <div className="bg-muted rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={250}
                  alt="Recipe Image"
                  className="w-full h-48 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Roasted Butternut Squash Soup</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A smooth and creamy soup made with roasted butternut squash and warm spices.
                  </p>
                </div>
              </div>
              <div className="bg-muted rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={250}
                  alt="Recipe Image"
                  className="w-full h-48 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Baked Ziti with Ricotta</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A comforting and cheesy baked pasta dish with a creamy ricotta sauce.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="bg-primary text-primary-foreground py-6">
        <div className="container">
          <div className="flex justify-between items-center">
            <p className="text-sm">&copy; 2024 Recipes Website</p>
            <nav>
              <ul className="flex gap-4">
                <li>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    About
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    Contact
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    Privacy Policy
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </footer>
    </div>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
